### ISSUE TITLE
missing serde feature

### ISSUE THREAD

**Issue by vincentserpoul** [dnaeon/rust-sshkeys#1]
Use case: I'm reading a "cloud-init" file with rust and was planning to Deserialize ssh keys with your lib, but it seems the Deserialize trait is missing.

**Comment by dnaeon** [comment]
Hi,

You could probably use https://docs.rs/sshkeys/0.1.1/sshkeys/struct.PublicKey.html#method.from_string in order to parsea public key from a given string.

**Comment by vincentserpoul** [comment]
First of all, thanks for the lib and thanks for the quick answer :)!
I need to look into it further as I'm far from being fluent in rust but it seems it can be done transparently.
I'm using https://github.com/steveklabnik/semver and https://doc.rust-lang.org/std/net/enum.IpAddr.html and the parsing is completely transparent.
If you re interested to add this feature, I can check how they work in these repos and do a PR, it's a good way to practice rust for me. Let me know!

**Comment by dnaeon** [comment]
I'd be happy to review a PR, so feel free to submit one! :) 

Also, could you please share example code that you need to get working?

Thanks!

**Comment by vincentserpoul** [comment]
sure:
https://github.com/chronotope/chrono-tz/blob/master/src/serde.rs
semver also uses the same "feature" https://github.com/steveklabnik/semver

other question: is there a reason why your Display function doesn't output the same as you would see in a .pub file?

**Comment by dnaeon** [comment]
> other question: is there a reason why your Display function doesn't output the same as you would see in a .pub file?

Not sure about that one, but we can change that if needed.
