### ISSUE TITLE
Release 0.3.3?

### ISSUE THREAD

**Issue by Firstyear** [dnaeon/rust-sshkeys#9]
It'd be great to see 0.3.3 if you want to do a release soon? Thanks!

**Comment by dnaeon** [comment]
Hey @Firstyear , I assume you mean this one?

* https://github.com/dnaeon/rust-sshkeys/pull/8/files

**Comment by Firstyear** [comment]
I meant a release on crates.io actually :) it's still 0.3.2 there from about 1 year ago https://crates.io/crates/sshkeys

**Comment by Firstyear** [comment]
Hey there, still waiting for this on crates.io :)

**Comment by dnaeon** [comment]
Hey @Firstyear ,

Sorry about that, totally missed this one.

Just tagged and published `v0.3.3` on crates.io.
